Make Maximum ID Value Explicit
PhilanthropyDataCommons/service pull request #1033
Opened 2024-05-24 17:26 UTC by hminsky2002

This commit adds an explicit maximum value for IDs, as we do not support IDs greater than 2^32-1. Note that as per the example provided in #971:
Before:
```
GET' \
  'http://localhost:3001/opportunities/555555555555555555555555555555' \
```
Returns
```
{
  "name": "DatabaseError",
  "message": "Unexpected database error.",
  "details": [
    {
      "length": 168,
      "name": "error",
      "severity": "ERROR",
      "code": "22003",
      "where": "unnamed portal parameter $1 = '...'",
      "file": "numutils.c",
      "line": "314",
      "routine": "pg_strtoint32"
    }
  ]
}
```
After:
```
GET' \
  'http://localhost:3001/opportunities/555555555555555555555555555555' \
```
Returns:
```
{
  "name": "InputValidationError",
  "message": "Invalid id parameter.",
  "details": [
    {
      "instancePath": "",
      "schemaPath": "#/maximum",
      "keyword": "maximum",
      "params": {
        "comparison": "<=",
        "limit": 4294967295
      },
      "message": "must be <= 4294967295"
    }
  ]
}
```
Closes #971

2024-07-10 17:17 UTC, bickelj approved these changes
Looks good to me. I did not try running it locally but I see no reason why this wouldn't work.

2024-07-10 19:06 UTC, slifty requested changes

2024-07-10 19:06 UTC, slifty commented on src/types/Id.ts
> +	maximum: 4294967295,
You should add a test for this (somewhere, doesn't have to be on all endpoint IMHO)

2024-07-16 21:30 UTC, hminsky2002 commented
@slifty a short test added in /src/__tests__/opportunities.int.test.ts line 83
```ts
it('returns 400 bad request when id is a number greater than 2^32-1', async () => {
			const result = await agent
				.get('/opportunities/555555555555555555555555555555')
				.set(authHeader)
				.expect(400);
			expect(result.body).toMatchObject({
				name: 'InputValidationError',
				details: expect.any(Array) as unknown[],
			});
		});
```

2024-07-17 16:43 UTC, merged