Add PUT and DELETE endpoints for UserFunderPermissions
PhilanthropyDataCommons/service pull request #1396
Opened 2024-12-30 21:06 UTC by slifty

This PR adds two new endpoints that make it possible to create and delete UserFunderPermissions in the PDC.

It uses the same patterns that were established for UserChangemakerPermissions

Related to #1250

2024-12-30 21:06 UTC, slifty commented
The swagger spec + changelog need to be updated before this can be merged.

2025-01-02 19:22 UTC, slifty commented on src/openapi.json
> +		"/users/{userKeycloakUserId}/fundera/{funderShortCode}/permissions/{permission}": {
`fundera` => `funders`

2025-01-03 20:34 UTC, hminsky2002 commented on src/__tests__/userFunderPermissions.int.test.ts
> -					`/users/${keycloakIdToString(user.keycloakUserId)}/fundera/${funder.shortCode}/permissions/${Permission.EDIT}`,
Methinks this should be in the previous commit

2025-01-03 20:35 UTC, hminsky2002 commented on src/__tests__/userFunderPermissions.int.test.ts
> +				createdBy: systemUser.keycloakUserId,
this also should be in the previous commit, methinks

2025-01-03 20:40 UTC, hminsky2002 requested changes
This looks good to me -- I tested locally and had all runs passing. I noticed two lines in the final commit that looked like they should be part of the previous commit and marked them as such!

2025-01-03 20:47 UTC, hminsky2002 commented
@slifty a question more than a comment -- as it stands since we use an upsert for a funder permission, is it true that a user and funder can only have one userFunderPermission entity between the two of them? If so, does that mean that the different permission levels (Manage and Edit) are meant to be structured hierarchically? I.e ever permission is a subset of a larger permission. That seems reasonable enough, but wanted to clarify if we're going to be adding more permissions further down the line.

2025-01-03 20:50 UTC, slifty commented
> @slifty a question more than a comment -- as it stands since we use an upsert for a funder permission, is it true that a user and funder can only have one userFunderPermission entity between the two of them? If so, does that mean that the different permission levels (Manage and Edit) are meant to be structured hierarchically? I.e ever permission is a subset of a larger permission. That seems reasonable enough, but wanted to clarify if we're going to be adding more permissions further down the line.

The primary key for UserFunderPermission is actually *three* things (the specific permission being the third thing).  So it's the case that there can only be one row per combindation of user + funder + permission (e.g. you can't grant edit twice, but you CAN grant edit and view).

2025-01-03 20:53 UTC, slifty commented
Good catches -- ready for re-review

2025-01-03 21:01 UTC, hminsky2002 approved these changes
Splendid, thanks @slifty

2025-01-03 21:27 UTC, merged

2025-01-06 21:42 UTC, bickelj reviewed
I'm a bit late. But I tried this locally after merge to main and it seemed to work as expected, both for bad/non-existent IDs and good/existing ones.